plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {

    // Cucumber
    testImplementation "io.cucumber:cucumber-java:7.15.0"
    testImplementation "io.cucumber:cucumber-testng:7.15.0"
    testImplementation 'io.cucumber:cucumber-junit:7.9.0'

    testImplementation "io.cucumber:cucumber-java:7.15.0"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:7.15.0"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    // RestAssured
    implementation "io.rest-assured:rest-assured:5.4.0"
    testImplementation "io.rest-assured:json-path:5.4.0"
    testImplementation "io.rest-assured:json-schema-validator:5.4.0"

    // TestNG
    testImplementation "org.testng:testng:7.9.0"

    // Logging
    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'

    // Allure (optional)
    testImplementation 'io.qameta.allure:allure-cucumber7-jvm:2.27.0'
    testImplementation "org.testng:testng:7.9.0"
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnitPlatform()
}